apiVersion: apps/v1
kind: Deployment
metadata:
  name: serving-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: serving
  template:
    metadata:
      labels:
        app: serving
    spec:
      containers:
      - name: serving
        image: serving:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
